US6 T8 connect frontend and backend for student evaluations
SOEN341-F24-CodeBusters/PeerAssessmentSystem pull request #100
Opened 2024-11-14 22:05 UTC by tinaw1412

2024-11-15 01:14 UTC, LouisChoiniere requested changes

2024-11-15 01:14 UTC, LouisChoiniere commented on CodebustersPAS-ClientApp/src/pages/CourseEvaluation/GroupEvaluation.jsx
> +        const teamList = data[0]?.studentList || [];
Why only first group? If the student is in multiple groups, only the first one will show.

2024-11-27 04:37 UTC, Theos1010 approved these changes
Good

2024-11-27 04:43 UTC, LouisChoiniere approved these changes
Good

2024-11-27 04:44 UTC, merged