15 setup course listing students
SOEN341-F24-CodeBusters/PeerAssessmentSystem pull request #47
Opened 2024-09-28 20:06 UTC by OmarSelim01

Setup the add member popup as well as the create team popup in the same page for both instructors and students, css overlapping issue for both popups resolved as well

2024-09-28 20:28 UTC, Theos1010 approved these changes

2024-09-29 01:13 UTC, LouisChoiniere requested changes
Fix comment otherwise looks good

2024-09-29 01:13 UTC, LouisChoiniere commented on CodebustersPAS-ClientApp/src/pages/Teacher/CreateTeam/TeamOverview.tsx
Why did you commit an empty file?

2024-09-29 16:24 UTC, LouisChoiniere approved these changes
lgtm

2024-09-29 21:45 UTC, Theos1010 reviewed
@OmarSelim01 When I run from your branch, on the Login page the "Don't have an account?" text isn't getting displayed anymore. Same happens with the "Already have an account?" on the Register page.

2024-09-30 02:12 UTC, merged