Sprint1 pacific
SOEN341-F24-CodeBusters/PeerAssessmentSystem pull request #53
Opened 2024-10-02 19:00 UTC by Paciflow

These are the codes I've written in GitHub In pair programming with Omar using react.

2024-10-02 23:07 UTC, OmarSelim01 approved these changes

2024-10-02 23:19 UTC, Theos1010 commented on README.md
@LouisChoiniere If this PR gets approved, will this commit on Readme overwrite what is currently in the Readme on main branch?
If so, @Paciflow should remove it

2024-10-02 23:57 UTC, LouisChoiniere commented on README.md
No, this will not revert the changes that you made on the readme file since there is no merge conflicts, but I don't see why the changes on this PR are necessary they should be removed. @Theos1010

2024-10-03 00:08 UTC, LouisChoiniere requested changes
You created a component/page, but it is not used anywhere? Needs to be fixed before merging.

Also undo changes on README

2024-10-03 00:08 UTC, LouisChoiniere commented on README.md
> +| Valeriia Nikandrova | 40157880 | Frontend |
Not sure why these changes on the readme are necessary, should be removed

2024-10-03 13:10 UTC, LouisChoiniere approved these changes

2024-10-03 21:07 UTC, merged