Created the frontend for Login & Create Account pages
SOEN341-F24-CodeBusters/PeerAssessmentSystem pull request #8
Opened 2024-09-24 02:06 UTC by Theos1010

Created Login Page for both Instructor and Student (Username, Password, Sign In and Create new account)
Created Register Page for both Instructor and Student (First name, Full name, Student ID, Username, Password, Sign Up and Sign In if already have an account)

2024-09-24 15:48 UTC, LouisChoiniere requested changes
Fix comment otherwise looks good

2024-09-24 15:48 UTC, LouisChoiniere commented on CodebustersPAS-ClientApp/src/pages/LoginPage.tsx
> +          <a href="/signup">Create one</a>
You should use `onClick={() => navigate('/')}` like on the create account page

2024-09-25 02:32 UTC, Theos1010 commented on CodebustersPAS-ClientApp/src/pages/CreateAccountPage.tsx
> +            <label htmlFor="lastName">Full Name</label>
@tinaw1412 Full Name hasn't been changed here

2024-09-25 02:51 UTC, Theos1010 commented on CodebustersPAS-ClientApp/src/pages/CreateAccountPage.tsx
>                placeholder="Enter your full name"
@tinaw1412 Change full name to last name here

2024-09-25 20:26 UTC, LouisChoiniere approved these changes

2024-09-25 20:28 UTC, tinaw1412 approved these changes

2024-09-25 20:34 UTC, merged